const mongoose = require('mongoose');
const Question = require('./model/questions');

require('dotenv').config(); 
// MongoDB connection
mongoose.connect(process.env.MONGODB_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  

const sampleQuestions = [

  // Sample question data for Quantitative Aptitude
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 15% of 200?',
    options: {
      a: '20',
      b: '30',
      c: '25',
      d: '35',
    },
    correctAnswer: 'b',  // Add the correct answer field
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If a train travels 120 km in 2 hours, what is its speed?',
    options: { a: '50 km/h', b: '60 km/h', c: '70 km/h', d: '80 km/h' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the square root of 144?',
    options: { a: '10', b: '11', c: '12', d: '13' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If 5x = 60, what is the value of x?',
    options: { a: '10', b: '12', c: '15', d: '20' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the value of 9 + 8 * (10 / 2)?',
    options: { a: '37', b: '40', c: '45', d: '50' },
    correctAnswer: 'a',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If 20% of a number is 50, what is the number?',
    options: { a: '200', b: '220', c: '250', d: '300' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the LCM of 12 and 18?',
    options: { a: '36', b: '48', c: '72', d: '60' },
    correctAnswer: 'a',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the HCF of 8 and 12?',
    options: { a: '2', b: '4', c: '6', d: '8' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If a car covers 240 km in 4 hours, what is the speed of the car?',
    options: { a: '50 km/h', b: '55 km/h', c: '60 km/h', d: '65 km/h' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 75% of 160?',
    options: { a: '100', b: '110', c: '120', d: '150' },
    correctAnswer: 'd',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 1/3 of 90?',
    options: { a: '25', b: '30', c: '35', d: '40' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If the ratio of boys to girls in a class is 3:2, and there are 30 students, how many boys are there?',
    options: { a: '12', b: '15', c: '18', d: '20' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 20 squared?',
    options: { a: '200', b: '400', c: '600', d: '800' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'A man earns $5000 per month. If he spends $3000, what percentage of his earnings does he save?',
    options: { a: '40%', b: '50%', c: '60%', d: '70%' },
    correctAnswer: 'a',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the average of 12, 15, 18, and 21?',
    options: { a: '16', b: '18', c: '22', d: '15' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If x + 2 = 10, what is x?',
    options: { a: '6', b: '7', c: '8', d: '9' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'A person bought 3 books for $60. What is the price per book?',
    options: { a: '$15', b: '$20', c: '$25', d: '$30' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the area of a rectangle with length 5 m and width 3 m?',
    options: { a: '8 m²', b: '15 m²', c: '20 m²', d: '25 m²' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If a car travels 150 km in 3 hours, what is its speed?',
    options: { a: '45 km/h', b: '50 km/h', c: '55 km/h', d: '60 km/h' },
    correctAnswer: 'd',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 40% of 80?',
    options: { a: '20', b: '30', c: '32', d: '40' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the perimeter of a square with side 4 cm?',
    options: { a: '12 cm', b: '16 cm', c: '18 cm', d: '20 cm' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If x = 4 and y = 3, what is the value of 2x + 3y?',
    options: { a: '17', b: '18', c: '19', d: '20' },
    correctAnswer: 'a',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the simple interest on $2000 at 5% per year for 2 years?',
    options: { a: '$150', b: '$200', c: '$250', d: '$300' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If a = 3, b = 4, what is the value of a² + b²?',
    options: { a: '12', b: '25', c: '16', d: '24' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If 9x = 72, what is x?',
    options: { a: '6', b: '7', c: '8', d: '9' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If the perimeter of a square is 32 cm, what is the length of one side?',
    options: { a: '8 cm', b: '7 cm', c: '6 cm', d: '9 cm' },
    correctAnswer: 'a',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 35% of 500?',
    options: { a: '150', b: '175', c: '180', d: '200' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If 10% of a number is 25, what is the number?',
    options: { a: '200', b: '220', c: '240', d: '250' },
    correctAnswer: 'd',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the cube of 3?',
    options: { a: '9', b: '12', c: '27', d: '18' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If x = 10 and y = 5, what is the value of 3x - 2y?',
    options: { a: '10', b: '15', c: '20', d: '25' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the square of 15?',
    options: { a: '200', b: '225', c: '250', d: '275' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the HCF of 18 and 24?',
    options: { a: '6', b: '8', c: '10', d: '12' },
    correctAnswer: 'a',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 5% of 200?',
    options: { a: '5', b: '10', c: '15', d: '20' },
    correctAnswer: 'd',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the product of 12 and 5?',
    options: { a: '50', b: '55', c: '60', d: '65' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If a car covers 80 km in 2 hours, what is its speed?',
    options: { a: '30 km/h', b: '35 km/h', c: '40 km/h', d: '45 km/h' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the LCM of 15 and 25?',
    options: { a: '75', b: '100', c: '125', d: '150' },
    correctAnswer: 'a',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 45% of 400?',
    options: { a: '150', b: '180', c: '200', d: '220' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If 4x = 100, what is x?',
    options: { a: '20', b: '22', c: '24', d: '25' },
    correctAnswer: 'd',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the area of a circle with radius 7 m? (Use π = 3.14)',
    options: { a: '148.64 m²', b: '153.86 m²', c: '154 m²', d: '160 m²' },
    correctAnswer: 'b',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is 25% of 600?',
    options: { a: '125', b: '130', c: '140', d: '150' },
    correctAnswer: 'd',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If a man earns $5000 in 5 months, what is his monthly income?',
    options: { a: '$800', b: '$900', c: '$1000', d: '$1100' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the simple interest on $1000 at 4% per annum for 3 years?',
    options: { a: '$120', b: '$140', c: '$160', d: '$180' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'What is the square of 25?',
    options: { a: '500', b: '600', c: '625', d: '650' },
    correctAnswer: 'c',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If a = 5 and b = 6, what is the value of 3a + 2b?',
    options: { a: '27', b: '28', c: '29', d: '30' },
    correctAnswer: 'a',
  },
  {
    section: 'Quantitative Aptitude',
    questionText: 'If the ratio of apples to oranges is 3:5 and there are 40 fruits, how many apples are there?',
    options: { a: '12', b: '15', c: '18', d: '20' },
    correctAnswer: 'b',
  },

// Sample question data for Logical Reasoning

{
  section: 'Logical Reasoning',
  questionText: 'If all cats are animals and some animals are lions, which of the following is true?',
  options: {
    a: 'All lions are cats',
    b: 'Some cats are lions',
    c: 'Some lions are animals',
    d: 'All animals are lions',
  },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'If the code for CAT is DBU, what is the code for DOG?',
  options: {
    a: 'EPI',
    b: 'EPH',
    c: 'FOG',
    d: 'DOL',
  },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'Which number comes next in the series: 2, 6, 12, 20, 30?',
  options: { a: '36', b: '42', c: '44', d: '40' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'If A is taller than B and B is taller than C, who is the shortest?',
  options: { a: 'A', b: 'B', c: 'C', d: 'Cannot be determined' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'If 3 pencils cost $1.50, how much will 12 pencils cost?',
  options: { a: '$4.50', b: '$6.00', c: '$5.00', d: '$4.80' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'John, Paul, and George are brothers. John is older than Paul, and Paul is older than George. Who is the youngest?',
  options: { a: 'John', b: 'Paul', c: 'George', d: 'Cannot be determined' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'What comes next in the sequence: A, C, E, G?',
  options: { a: 'H', b: 'I', c: 'J', d: 'K' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'If P is the sister of Q and Q is the son of R, what is R to P?',
  options: { a: 'Father', b: 'Mother', c: 'Brother', d: 'Cannot be determined' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'A clock shows 3:00 PM. What is the angle between the hour hand and the minute hand?',
  options: { a: '45 degrees', b: '90 degrees', c: '120 degrees', d: '180 degrees' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'If a cube has a side length of 3 cm, what is its volume?',
  options: { a: '9 cm³', b: '18 cm³', c: '27 cm³', d: '36 cm³' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'Which word does not belong to the group: Apple, Banana, Grape, Carrot?',
  options: { a: 'Apple', b: 'Banana', c: 'Grape', d: 'Carrot' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'Which number does not belong in the series: 2, 5, 10, 17, 26?',
  options: { a: '5', b: '10', c: '17', d: '26' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'If x is twice as large as y, and y is half as large as z, what is the ratio of x to z?',
  options: { a: '1:1', b: '2:1', c: '4:1', d: '2:2' },
  correctAnswer: 'a',
},
{
  section: 'Logical Reasoning',
  questionText: 'Find the missing number: 5, 10, 15, __, 25',
  options: { a: '20', b: '22', c: '18', d: '21' },
  correctAnswer: 'a',
},
{
  section: 'Logical Reasoning',
  questionText: 'In a family of six people, A is the father of B, and B is the father of C. What is A to C?',
  options: { a: 'Father', b: 'Grandfather', c: 'Uncle', d: 'Brother' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'Which letter is midway between G and O in the alphabet?',
  options: { a: 'I', b: 'J', c: 'K', d: 'L' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'What number comes next in the series: 1, 4, 9, 16, 25?',
  options: { a: '30', b: '36', c: '49', d: '44' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'If the second day of a month is a Tuesday, what will be the fifth day?',
  options: { a: 'Wednesday', b: 'Thursday', c: 'Friday', d: 'Saturday' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'In a certain code, PEARL is written as QFBQM. How is STONE written in that code?',
  options: { a: 'TUPOF', b: 'TUPOF', c: 'TUPON', d: 'SOTNE' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'A bus travels at 60 km/h for 2 hours and then at 50 km/h for 3 hours. What is the average speed?',
  options: { a: '53 km/h', b: '55 km/h', c: '56 km/h', d: '58 km/h' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'Which word does not belong to the group: Pen, Pencil, Eraser, Paper?',
  options: { a: 'Pen', b: 'Pencil', c: 'Paper', d: 'Eraser' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'If A is the brother of B and C, and B is the sister of C, what is C to A?',
  options: { a: 'Brother', b: 'Sister', c: 'Cousin', d: 'Cannot be determined' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'What comes next in the series: 2, 6, 12, 20, 30?',
  options: { a: '36', b: '40', c: '44', d: '50' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'In a certain code, BEAN is written as FIDC. How is WISH written in that code?',
  options: { a: 'ZLVP', b: 'YKUR', c: 'YMQR', d: 'ZMRP' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'What is the next letter in the series: A, E, I, M, Q?',
  options: { a: 'R', b: 'S', c: 'U', d: 'V' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'John is the son of Peter. Paul is Peter’s brother. What is John to Paul?',
  options: { a: 'Nephew', b: 'Son', c: 'Brother', d: 'Uncle' },
  correctAnswer: 'a',
},
{
  section: 'Logical Reasoning',
  questionText: 'If 7 = 2, 10 = 4, 12 = 6, then 15 =?',
  options: { a: '4', b: '5', c: '6', d: '7' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'A clock shows 9:15 AM. What is the angle between the hour hand and the minute hand?',
  options: { a: '97.5 degrees', b: '87.5 degrees', c: '92.5 degrees', d: '90 degrees' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'If Tom is taller than Harry and Harry is taller than Sally, who is the tallest?',
  options: { a: 'Tom', b: 'Harry', c: 'Sally', d: 'Cannot be determined' },
  correctAnswer: 'a',
},
{
  section: 'Logical Reasoning',
  questionText: 'What comes next in the series: B, D, F, H, __?',
  options: { a: 'J', b: 'K', c: 'I', d: 'L' },
  correctAnswer: 'a',
},
{
  section: 'Logical Reasoning',
  questionText: 'If a bus travels 200 km in 4 hours, what is its speed?',
  options: { a: '45 km/h', b: '50 km/h', c: '55 km/h', d: '60 km/h' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'What is the missing number: 7, 14, 21, __, 35?',
  options: { a: '25', b: '28', c: '30', d: '32' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'Which word does not belong to the group: Chair, Table, Bench, Plate?',
  options: { a: 'Chair', b: 'Table', c: 'Plate', d: 'Bench' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'What comes next in the sequence: 3, 6, 9, 12, 15, __?',
  options: { a: '16', b: '18', c: '20', d: '19' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'A clock shows 6:00. What is the angle between the hour hand and the minute hand?',
  options: { a: '45 degrees', b: '60 degrees', c: '90 degrees', d: '180 degrees' },
  correctAnswer: 'd',
},
{
  section: 'Logical Reasoning',
  questionText: 'If all dogs are animals and some animals are birds, which of the following is true?',
  options: { a: 'All dogs are birds', b: 'Some birds are dogs', c: 'Some dogs are animals', d: 'All animals are dogs' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'Which number is missing: 1, 4, 9, 16, __, 36?',
  options: { a: '20', b: '21', c: '25', d: '30' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'A man walks 5 km north, then 3 km east. How far is he from the starting point?',
  options: { a: '5 km', b: '6 km', c: '7 km', d: '8 km' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'In a certain code, ABC is written as DEF. How is GHI written in that code?',
  options: { a: 'JKL', b: 'HIK', c: 'JKM', d: 'LMN' },
  correctAnswer: 'a',
},
{
  section: 'Logical Reasoning',
  questionText: 'If the first day of a month is Sunday, what will be the 10th day?',
  options: { a: 'Tuesday', b: 'Wednesday', c: 'Monday', d: 'Thursday' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'Find the odd one out: Car, Bus, Train, Bicycle',
  options: { a: 'Car', b: 'Bus', c: 'Bicycle', d: 'Train' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'A man sells 2 watches for $80 each. On one, he gains 20%, and on the other, he loses 20%. What is the total loss or gain?',
  options: { a: '2% loss', b: 'No loss, no gain', c: '4% loss', d: '2% gain' },
  correctAnswer: 'c',
},
{
  section: 'Logical Reasoning',
  questionText: 'If x = 3 and y = 5, what is the value of 2x + y?',
  options: { a: '11', b: '13', c: '14', d: '15' },
  correctAnswer: 'b',
},
{
  section: 'Logical Reasoning',
  questionText: 'Find the missing letter in the series: C, D, E, F, __, H',
  options: { a: 'G', b: 'I', c: 'H', d: 'J' },
  correctAnswer: 'a',
},

// Sample question data for Verbal Ability

  {
    section: 'Verbal Ability',
    questionText: 'Choose the correct antonym for the word "Exuberant"',
    options: {
      a: 'Cheerful',
      b: 'Gloomy',
      c: 'Excited',
      d: 'Energetic',
    },
    correctAnswer: 'b',  // Add the correct answer field
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of the word "Pessimistic".',
    options: { a: 'Optimistic', b: 'Realistic', c: 'Skeptical', d: 'Cynical' },
    correctAnswer: 'a',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Choose the word that best completes the sentence: "The team was _______ after their victory."',
    options: { a: 'despondent', b: 'elated', c: 'apathetic', d: 'indifferent' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Find the synonym of the word "Benevolent".',
    options: { a: 'Cruel', b: 'Kind', c: 'Aggressive', d: 'Harsh' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of the word "Audacious".',
    options: { a: 'Bold', b: 'Courageous', c: 'Timid', d: 'Fearless' },
    correctAnswer: 'c',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Fill in the blank: "She is known for her _______ nature, always ready to help others."',
    options: { a: 'vindictive', b: 'benevolent', c: 'avaricious', d: 'insensitive' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Which word is the synonym of "Eloquent"?',
    options: { a: 'Inarticulate', b: 'Fluent', c: 'Confusing', d: 'Rough' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Choose the correct antonym for "Indolent".',
    options: { a: 'Lazy', b: 'Energetic', c: 'Idle', d: 'Slow' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the correct antonym of "Transient"?',
    options: { a: 'Temporary', b: 'Permanent', c: 'Evanescent', d: 'Momentary' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Select the correct synonym for "Resilient".',
    options: { a: 'Brittle', b: 'Flexible', c: 'Fragile', d: 'Rigid' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Choose the best word to complete the sentence: "His speech was filled with _______ remarks."',
    options: { a: 'sarcastic', b: 'sincere', c: 'disparaging', d: 'humorous' },
    correctAnswer: 'c',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Find the synonym for the word "Concur".',
    options: { a: 'Disagree', b: 'Argue', c: 'Agree', d: 'Contradict' },
    correctAnswer: 'c',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of "Affluent".',
    options: { a: 'Rich', b: 'Poor', c: 'Wealthy', d: 'Prosperous' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Fill in the blank: "The scientist\'s theory was met with _______ from his peers."',
    options: { a: 'apathy', b: 'skepticism', c: 'support', d: 'agreement' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Which word is a synonym for "Meticulous"?',
    options: { a: 'Careless', b: 'Accurate', c: 'Hasty', d: 'Clumsy' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of "Ambiguous".',
    options: { a: 'Clear', b: 'Vague', c: 'Confusing', d: 'Obscure' },
    correctAnswer: 'a',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the correct antonym of "Subtle"?',
    options: { a: 'Obvious', b: 'Nuanced', c: 'Delicate', d: 'Elusive' },
    correctAnswer: 'a',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Choose the correct synonym for the word "Prolific".',
    options: { a: 'Barren', b: 'Productive', c: 'Sparse', d: 'Unfruitful' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Find the antonym for "Innocuous".',
    options: { a: 'Harmless', b: 'Dangerous', c: 'Mild', d: 'Safe' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Fill in the blank: "Her _______ personality made her the center of attention at the party."',
    options: { a: 'reticent', b: 'gregarious', c: 'reclusive', d: 'shy' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Choose the word that best completes the sentence: "The _______ of the speech was inspiring."',
    options: { a: 'content', b: 'delivery', c: 'tone', d: 'length' },
    correctAnswer: 'c',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the synonym for "Ostentatious"?',
    options: { a: 'Modest', b: 'Flamboyant', c: 'Simple', d: 'Unpretentious' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of "Taciturn".',
    options: { a: 'Talkative', b: 'Quiet', c: 'Shy', d: 'Introverted' },
    correctAnswer: 'a',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Find the synonym for "Lucid".',
    options: { a: 'Confusing', b: 'Clear', c: 'Obscure', d: 'Ambiguous' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Which word best completes the sentence: "He was known for his _______ approach to solving problems."',
    options: { a: 'chaotic', b: 'methodical', c: 'random', d: 'disorganized' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of "Vigilant".',
    options: { a: 'Watchful', b: 'Alert', c: 'Careless', d: 'Attentive' },
    correctAnswer: 'c',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Choose the correct synonym for "Abundant".',
    options: { a: 'Scarce', b: 'Plentiful', c: 'Minimal', d: 'Inadequate' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Find the antonym of the word "Mundane".',
    options: { a: 'Ordinary', b: 'Exciting', c: 'Boring', d: 'Dull' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the synonym for "Inept"?',
    options: { a: 'Skilled', b: 'Clumsy', c: 'Talented', d: 'Adept' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of "Exuberant".',
    options: { a: 'Cheerful', b: 'Depressed', c: 'Energetic', d: 'Lively' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Choose the correct synonym for "Voracious".',
    options: { a: 'Satiated', b: 'Hungry', c: 'Apathetic', d: 'Indifferent' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the antonym of "Erudite"?',
    options: { a: 'Ignorant', b: 'Educated', c: 'Knowledgeable', d: 'Informed' },
    correctAnswer: 'a',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Fill in the blank: "The manager gave a _______ explanation of the project."',
    options: { a: 'concise', b: 'verbose', c: 'confusing', d: 'vague' },
    correctAnswer: 'a',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of "Frugal".',
    options: { a: 'Economical', b: 'Thrifty', c: 'Lavish', d: 'Cheap' },
    correctAnswer: 'c',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the synonym of "Impartial"?',
    options: { a: 'Biased', b: 'Fair', c: 'Prejudiced', d: 'Partisan' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Find the antonym of "Conspicuous".',
    options: { a: 'Prominent', b: 'Noticeable', c: 'Hidden', d: 'Visible' },
    correctAnswer: 'c',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Choose the correct synonym for "Ambiguous".',
    options: { a: 'Clear', b: 'Vague', c: 'Obvious', d: 'Apparent' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Which word best completes the sentence: "Her _______ attitude made her a favorite among her colleagues."',
    options: { a: 'rude', b: 'amiable', c: 'aloof', d: 'indifferent' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Find the synonym for "Tacit".',
    options: { a: 'Expressed', b: 'Silent', c: 'Loud', d: 'Obvious' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of "Prudent".',
    options: { a: 'Wise', b: 'Cautious', c: 'Reckless', d: 'Sensible' },
    correctAnswer: 'c',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the synonym of "Lucid"?',
    options: { a: 'Clear', b: 'Confusing', c: 'Ambiguous', d: 'Vague' },
    correctAnswer: 'a',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the antonym of "Obscure"?',
    options: { a: 'Uncertain', b: 'Clear', c: 'Complicated', d: 'Vague' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Which word best completes the sentence: "The _______ nature of the material made it difficult to read."',
    options: { a: 'clear', b: 'opaque', c: 'transparent', d: 'obvious' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Identify the antonym of "Arrogant".',
    options: { a: 'Humble', b: 'Proud', c: 'Boastful', d: 'Confident' },
    correctAnswer: 'a',
  },
  {
    section: 'Verbal Ability',
    questionText: 'Find the synonym for "Gregarious".',
    options: { a: 'Shy', b: 'Sociable', c: 'Reserved', d: 'Timid' },
    correctAnswer: 'b',
  },
  {
    section: 'Verbal Ability',
    questionText: 'What is the synonym for "Amiable"?',
    options: { a: 'Hostile', b: 'Friendly', c: 'Rude', d: 'Unfriendly' },
    correctAnswer: 'b',
  }
];

// Insert data into MongoDB
Question.insertMany(sampleQuestions)
  .then(() => {
    console.log('Questions added successfully!');
    mongoose.connection.close();
  })
  .catch((error) => {
    console.log('Error inserting questions:', error);
  });
